windowrule = match:class (brave-browser), workspace 2
windowrule = match:class (chromium), workspace 2
windowrule = match:class (firefox), workspace 2
windowrule = match:class (Mullvad Browser), workspace 2
windowrule = match:class (zen), workspace 2

windowrule = match:class (Alacritty), workspace 3
windowrule = match:class (com.mitchellh.ghostty), workspace 3
windowrule = match:class (foot), workspace 3
